---
author: Alexander Höreth
year: 2016
department: Institut für Kognitionswissenschaft // Institut für Informatik
university: Universität Osnabrück
title: Konzeptualisierung und Entwicklung einer Web-Applikation zur interaktiven Navigation deutscher Bundesgesetze
subtitle: Moderne Werkzeuge für Juristen
supervisor: Prof. Dr. Oliver Vornberger, Universität Osnabrück
university_logo: img/uos.png

documentclass: scrbook
fontfamily: libertine
link-citations: True

# https://github.com/lierdakil/pandoc-crossref#code-block-labels
listings: True
codeBlockCaptions: True
lstPrefix:
  -
  -
secPrefix:
  - Abschnitt
  -
---
