---
author: Alexander Höreth
year: 2016
degree: Cognitive Science, Bachelor of Science
departments:
  - Institut für Kognitionswissenschaft
  - Institut für Informatik
  # - Department of Cognitive Science
  # - Department of Computer Science
university: Universität Osnabrück
  # University of Osnabrück
title: Konzeptualisierung und Entwicklung einer Web-Applikation zur interaktiven Navigation deutscher Bundesgesetze
  # Conceptualization and implmeentation of a web-application for interactive navigation of German federal law
subtitle: Moderne Werkzeuge für Juristen
supervisors:
  - "Erstprüfer: Prof. Dr. Oliver Vornberger"
  - "Zweitprüfer: Dr. phil. Tobias Thelen"
  # - "Primary supervisor: Prof. Dr. Oliver Vornberger"
  # - "Secondary supervisor: Dr. phil. Tobias Thelen"
university_logo: img/uos2.eps

documentclass: scrbook
fontfamily: libertine
link-citations: True

# https://github.com/lierdakil/pandoc-crossref#code-block-labels
listings: True
codeBlockCaptions: True
lstPrefix:
  -
  -
secPrefix:
  - Abschnitt
  -
---
